[package]
name = "amplify-backend"
version = "0.1.0"
edition = "2021"

[features]
default = ["db-sqlite"]
db-sqlite = ["dep:rusqlite", "refinery/rusqlite"]
db-postgres = ["dep:postgres", "refinery/postgres"]

[dependencies]
actix-cors = "0.7"
actix-web.workspace = true
dirs = "5"
refinery = { version = "0.8", default-features = false }
postgres = { version = "0.19", optional = true }
rusqlite = { version = "0.32", features = ["bundled"], optional = true }
serde.workspace = true
serde_json.workspace = true
shared-types = { path = "../shared-types" }
sysinfo = "0.33"
tokio = { version = "1", features = ["sync", "rt", "time", "macros"] }
which = "7"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"
